version: '3.9'

services:
  # Servicio de MySQL
  mysql:
    image: mysql:8.0
    container_name: gastos_confeccion_mysql
    environment:
      MYSQL_ROOT_PASSWORD: Gonorrea007
      MYSQL_DATABASE: confecciondb
      MYSQL_USER: MrZyzz23
      MYSQL_PASSWORD: Gonorrea007
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    networks:
      - gastos_network

  # Servicio FastAPI
  app:
    build: .
    container_name: gastos_confeccion_app
    environment:
      DATABASE_URL: mysql+pymysql://usuario:contrase√±a123@mysql:3306/gastos_confeccion
    ports:
      - "8001:8001"
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - .:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8001 --reload
    networks:
      - gastos_network

volumes:
  mysql_data:

networks:
  gastos_network:
    driver: bridge
